### ISSUE TITLE
Unnecessary and wrong if statements on neologd2juman.sh

### ISSUE THREAD

**Issue by kakakaya** [fumankaitori/neologd2juman#3]
https://github.com/fumankaitori/neologd2juman/blob/master/neologd2juman.sh#L20-L31

If arguments length is 1, this statements passes. But, if arguments length is 2, the first if statement fails. Have you tested this script with two arguments?

My suggestion is deleting first if statements as below, this will work fine.

```
if [ $# -eq 1 ]; then
    input_base=`basename $1`
elif [ $# -eq 2 ]; then
    input_base=`basename $1`
    juman_utils_bin=$2
else
    echo "[Error] Usage: ./neologd2juman.sh INPUT_neologd [juman-installed-path]"
    exit 1
fi
```

**Comment by Kensuke-Mitsuzawa** [comment]
@kakakaya Sorry to be late for my reply. Thank you for your suggestion. As you pointed out, the first if block should be deleted. Your suggestion is on code by PR5 https://github.com/fumankaitori/neologd2juman/pull/5
